[package]
name = "kintone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.3"
bigdecimal = { version = "0.4.1", features = ["serde"] }
chrono = { version = "0.4.28", features = ["serde"] }
enum-assoc = "1.1.0"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
serde = { version = "1.0.188", features = ["derive"] }
thiserror = "1.0.47"
url = "2.4.1"
